### ISSUE TITLE
Regarding to get Private key and Public.cre file

### ISSUE THREAD

**Issue by PremalathaKumar** [mobilpay/prestashop#1]
I'm using Mobilpay card Gateway for the woocommerce plugin. I want to test this plugin in a sandbox environment. But I'm not a business organizer. I'm a developer. so I don't have a mobilpay account. How can I get the private key and public.cre file. Is there any way to get this without the account. or I'm ready to create the account. But it asking so may field to fill. Is there any way to do this.
Please help me!!

**Comment by andreipanait** [comment]
On top of public and private keys you would also need a private merchant signature. The only way to get these is by [signing up on mobilPay](https://www.mobilPay.ro/register-m) and creating your own merchant account.

**Comment by PremalathaKumar** [comment]
Thanks for your reply. I have a doubt. For sandbox testing also do I need to fill all the fields. Or It has a separate option for personal account something else.

**Comment by andreipanait** [comment]
Yes, all fields are used for both live and sandbox orders. Signature is the same, private and public keys are different though.
