### ISSUE TITLE
compatibilitate  prestashop 8.x

### ISSUE THREAD

**Issue by mnick73** [mobilpay/prestashop#10]
Buna ziua,

In urma update-ului la presta 8 atat versiunea de modul 1 cat si 1.1 nu mai functioneaza corect. mai exact redirectionare inapoi catre site dupa acceptarea platii.

-in presta 1.7.x.x redirectionarea se face catre pagina de confirmare comanda. url de genul

https://www.domeniu.ro/confirmare-comanda?id_cart=166693&id_module=127&orderId=166693%25231721&key=1d87e50c75a91f8
(pentru protectie parte din caractere au fost eliminate)

-in presta 8.x.x redirectionarea se face in contul clientului istoric comenzi

https://www.domeniu.ro/istoric-comenzi pentru clienti existent.

Exista o versoiune pentru presta 8?

**Comment by vaerlor** [comment]
Am scris la suport din februarie 2024, am primit raspuns, dar inca nu e solutionata problema.
Eu nici macar nu am reusit sa instalez modulul in versiunea 8.x

**Comment by dark2y** [comment]
Salut. Poti edita de mana fisierul referentiat de mine aici daca nu iti raspund. https://github.com/mobilpay/prestashop/issues/11

**Comment by mnick73** [comment]
Eu am vorbit la suport si mi-au transmis ca trimit catre dezvoltare, insa nu s-a mai dezvoltat nimic din iulie. Am trecut la alt procesator cu raspuns in 24 ore cu comision mai mic si ramburs instant. Tot raul spre bine!

**Comment by dark2y** [comment]
Da. Am observat abia acum ca dupa ce e rezolvat typo-ul acela tot nu merge mai departe din alte cauze mai jos in cod; Concluzia este ca e incompatibil cu Presta 8.x la partea de confirmare comanda.

**Comment by navid59** [comment]
Thank you for mentioning the problem.
Apologies for the late response.

The module has been updated.
It has been tested up to version 8.1.7.
