### ISSUE TITLE
There is a typo in this file that prevents the order sucess page to be displayed

### ISSUE THREAD

**Issue by dark2y** [mobilpay/prestashop#11]
https://github.com/mobilpay/prestashop/blob/2199d8f358b6dfe7f40f03a87bdb86fdbcfd2d34/1.7.7/mobilpay_cc/mobilpay_cc.php#L427

**Comment by dark2y** [comment]
There is a additional "?" in `index.php?controller=order-confirmation?key=`
This code should be `index.php?controller=order-confirmation&amp;key=`

**Comment by navid59** [comment]
Thank you for mentioning the problem.

The module has been updated.
It has been tested up to version 8.1.7.
