### ISSUE TITLE
Unable to upload the module

### ISSUE THREAD

**Issue by mflorin** [mobilpay/prestashop#2]
Hello,

I've been following the installation instructions from INSTALL.txt where it says:
1. upload the files from files folder 
2. go to admin->payment section and press install for your desired mobilPay payment module

I've tried zipping the contents of the repo using different layouts but prestashop keeps throwing the same error:
"This file does not seem to be a valid module zip".

Also, there's no files folder as specified in the first step.

Can you help installing this module please?

Thanks.

**Comment by andreipanait** [comment]
Hello,

The plugin cannot be uploaded as .zip directly in your admin, you should upload the files using your preferred FTP client (or unzip them) to your Prestashop modules folder. Create a folder named `mobilpay_cc` there, then upload the contents of `master/modules/mobilpay` 

You can always download the plugin dedicated to your Prestashop version from your Netopia account under the menu Implementation - Examples (highly recommended)

Do let us know if any other problems arise.

**Comment by mflorin** [comment]
Thank you for the quick reply, I'll try that.
