### ISSUE TITLE
Prestashop version 1.7.7.4 not work

### ISSUE THREAD

**Issue by storygram** [mobilpay/prestashop#4]
I am trying to install this module on Prestashop version 1.7.7.4 and it does not work, please help me

**Comment by navid59** [comment]
The module is comaptible with Prestashop version 1.7.7.4 too

Please, follow the steps in document
https://github.com/mobilpay/prestashop/blob/master/Docs/manual_install_EN%20v.1.7.pdf

**Comment by storygram** [comment]
I followed all the steps :( , you need an upgrade to this mobipay module, it doesn't work on prestashop version 1.7.7.4

**Comment by andreipanait** [comment]
You need to provide more info as to what doesn't work for you. The plugin works just fine.
