### ISSUE TITLE
 Reason:error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by cosminw** [mobilpay/prestashop#6]
Salutare,
Avem urmatoarea eroare in pagina de finalizare comanda:
`Exception {#1850 ▼
  #message: "Error while encrypting data! Reason:error:0308010C:digital envelope routines::unsupported\n"
  #code: 268435458
  #file: "xx/public_html/modules/mobilpay_cc/Mobilpay/Payment/Request/Abstract.php"
  #line: 340
  trace: {▼
    xx/public_html/modules/mobilpay_cc/Mobilpay/Payment/Request/Abstract.php:340 {▼
      › \t}
      › \tthrow new Exception($errorMessage, self::ERROR_ENCRYPT_DATA);
      › }
    }`
Din discutile cu serviciul de hosting au facut update pentru OpenSSL de la versiunea 1.1.1 la 3.0.8.
Va rog o solutie pentru aceasta problema.
Multumesc anticipat

**Comment by andreipanait** [comment]
Salutare, 

Pentru aceasta problema solutia o reprezinta utilizarea OpenSSL 3.x cu [legacy providers](https://www.openssl.org/docs/man3.0/man7/OSSL_PROVIDER-legacy.html) sau utilizarea [1.1.1t](https://www.openssl.org/source/openssl-1.1.1t.tar.gz) aflat in LTS pana in Septembrie 2023.

Pe termen mediu vom migra pluginurile curente, inclusiv pe acesta de Prestashop, catre un alt API care nu mai foloseste functii OpenSSL

Spor!

**Comment by FreezeS** [comment]
Salut,
Aveti un tutorial pentru Apache2 - Ubuntu 22.04, ca nu gasesc niciunde fara recompilare apache din surse.

--- sau ---

Cand va fi migrat pluginul de prestashop? (ca sa nu ma mai dau cu capul de pereti degeaba)
