### ISSUE TITLE
NU SE POATE INSTALA

### ISSUE THREAD

**Issue by Dori1993** [mobilpay/prestashop#7]
Buna ziua,
Ma chiuni cu modulul sa-l instalez si nu reusesc nicicum.
Ma puteti ajuta? Va rog din suflet!

**Comment by Dori1993** [comment]
Mentionez ca folosesc  Presta 1.7.8.8

**Comment by Dori1993** [comment]
Daca il trag direct fisierul ZIP in module nu se instaleaza, am incercat sa fac un FOLDER IN PUBLIC HTML--> MODULES--> Am creat aici folderul MOBILPAY_CC, si orice am copiat aici sau am dezarhivat aici, nu apare nicaieri in admin sa pot instala modulul de undeva.
Va rog sa ma ajutati!

**Comment by Dori1993** [comment]
HELP PLEASE!

**Comment by andreipanait** [comment]
Pasii de instalare se regasesc aici https://github.com/mobilpay/prestashop/tree/master/Docs/manual_instalare_RO%20v.1.7.pdf

Pluginul poate fi instalat atat prin installer-ul prestashop (se incarca direct fisierul .zip sau conform instructiunilor din doc). 

Pentru suport va rugam sa contactati implementare@netopia.ro

**Comment by Dori1993** [comment]
Buna ziua,
Multumesc pentru raspuns!
Nu merge nici prin instaler din admin, incarcand fisierul zip, apare eroare, iar daca fac conform pasilor, nu apare modulul mobilpay in admin sa il pot instala, chiar daca copiez fisierele prin FTP conform documentatiei.
Va rog sa ma ajutati!
